import type { Metadata } from 'next';
import './globals.css';
import { Login } from '@/components/login';
import { TopMenu } from '@/components/top-menu';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={'mt-16'}>
        <>
          <TopMenu />
          <Login />
          {children}
        </>
      </body>
    </html>
  );
}
